import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import portfolioConfig from '@/utils/config'
import { iconMap } from '@/components/Portfolio'
import { useRouter, usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				style={{ backgroundColor: '#022c22' }}
				className={`${inter.className}`}>
				{children}
			</body>
		</html>
	)
}
